# Generated by Django 4.0.4 on 2022-05-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_post_mainphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
